### ISSUE TITLE
Déclaration d'échange de bien

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/Portail-SDPV#17]
A la suite du contrôle fiscale de SDPV nous avons été informé que nous sommes tenu de faire une déclaration auprès des douanes sur les pièces qui sont importés de pays de la zone Euro.

Ces pièces ont une référence douanière que nous avons récupérée

 de ces fournisseurs et qui est maintenant dans la fiche article, exemple en pièce jointe.

cette information et à mettre à disposition dans le reporting  SDPV 

Bertrand se charge d’éditer le tableau que demande la douane qui est également en pièce jointe.
![code douane](https://user-images.githubusercontent.com/22592053/29555772-f0b1e5ca-8723-11e7-8bc2-09ac783f950b.JPG)

[12DEB.txt](https://github.com/groupe-gac/Portail-SDPV/files/1241297/12DEB.txt)
ce fichier doit être au format csv

**Comment by meillere** [comment]
SELECT        fournisseur.societe, Invoice.Journal, Invoice.InvoiceDate, InvoiceDetail.Qte, InvoiceDetail.HT20,  Invoice.VATLaw, Invoice.Pays
FROM            Invoice INNER JOIN
                         fournisseur ON Invoice.IDFournisseur = fournisseur.idfournisseur INNER JOIN
                         InvoiceDetail ON Invoice.ID = InvoiceDetail.InvoiceID
WHERE        (Invoice.Journal = 'ACPR') and VATlaw<>1
