### ISSUE TITLE
Recherche de référence avec 4 caractères

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/Portail-SDPV#3]
Remonté par Alexiane : 

> 
> Bonjour Messieurs,
> 
> Il y aurait 'il une solution à apporter concernant le problème ci-dessous ?
> 
> Je vous remercie pour votre retour.
> 
> Cordialement
> 
> Alexiane
> 
> -----Message d'origine-----
> De : jlm@way-bis.com [mailto:jlm@way-bis.com]
> Envoyé : jeudi 1 décembre 2016 09:20
> À : jlm@way-bis.com; Francois Beauchesne <francois.beauchesne@sdpv.com>; Jean-Luc Seris <jl.seris@sdpv.com>; jlm@way-bis.com; Alain Pierre <alain.pierre@sdpv.com>; Alexiane Bastide <alexiane.bastide@sdpv.com>; Willy Rance <willy.rance@sdpv.com>; Eric Tetet <eric.tetet@sdpv.com>
> Objet : Texte libre ci-dessous à remplir
> 
> Objet Message : Suggestion(s) - Texte libre ci-dessous à remplir
> 
>  Texte : Bonjour,depuis quelque temps la recherche par "commence par" et par "contient" ne fonctionne qu'avec 8 caractères.Ces fonctions ne servent donc plus (fin de reference ou debut illisible).Pouvez vous remetre le logiciel a 4 caractères.
> 
>  Provenance : CHAPELIER S.A. - M CHRISTOPHE PRE  Concession : CHAPELIER S.A. - M CHRISTOPHE PRE
> 
> Tel :
> 
> idutilisateur : 1969
> expéditeur : christophe.pre@chapelier.fr

**Comment by MamboJoel** [comment]
Malheureusement nous n'avons aucune trace de la discussion et des considérations qui nous ont amenées à passer le nombre de caractères minimums de 4 à 8. Il me semble que c'était un problème processeur.

@meillere tu te souviens ?

**Comment by Alexiane** [comment]
Bonjour,

Réponse de Paulhac à ce sujet hier : 

"ceci est lié à la dernière fois. soit je retire commence / contient, soit je laisse comme ça. (à voir avec Nicolas / Mr Meillere)

car je sais qu'à partir de 8 caractères, la requête ne tourne pas aussi longtemps ! (3 caractères, je crois c'est plusieurs minutes !)

cela fera bug la page de recherche"

**Il faudrait donc trouver une solution alternative pour que j'ai la possibilité de rentrer 8 caractères sans que cela rame.

Merci**

**Comment by MamboJoel** [comment]
On fait un point avec Jacques à son retour mercredi.

**Comment by Paulhac** [comment]
Bonjour,

je viens de modifier la recherche. à partir de 5 caractères pour "commence par" et "contient"


cdt,

**Comment by Alexiane** [comment]
Merci Paulhac,

Et à partir de 4 caractère est-ce possible ? (demande du franchisé)

**Comment by Paulhac** [comment]
je viens de tester à partir de 4 caractères, j'ai eu des lenteurs. donc je laisse 5 caractères mini.
