### ISSUE TITLE
Gestion des utilisateurs Scouarnec / Kehr Trucks. Sécurité.

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/Portail-SDPV#4]
@AlainPierreSDPV c'est plus compliqué que ça. Le fichier source : [Mutation user  scouarnec KLS.xlsx](https://github.com/groupe-gac/Portail-SDPV/files/723918/Mutation.user.scouarnec.KLS.xlsx)

Car il faut prendre en compte les accès.
Par exemple le User 476 est présent une fois dans ton fichier. Or dans la base de données il est présent deux fois. Une fois à la concession 16 avec pour accès 2. Une fois à la concession 16 avec pour accès 4.

Les affectations actuelles des utilisateurs de ton fichier :

```
idacces	idconcession	idutilisateur
2	41	344
3	41	344
4	41	344
2	81	346
3	81	346
4	81	346
2	16	475
4	16	475
2	16	476
4	16	476
1	81	836
2	81	836
3	81	836
1	81	1655
2	81	1655
3	81	1655
1	39	2114
2	39	2114
3	39	2114
1	81	2125
2	81	2125
3	81	2125
1	41	2603
2	41	2603
14	41	2603
1	39	2849
2	39	2849
1	150	2873
2	150	2873
4	150	2873
13	150	2873
1	395	2891
2	395	2891
3	395	2891
1	40	3031
2	40	3031
4	40	3031
13	40	3031
2	81	3959
14	81	3959
2	40	4044
14	40	4044
2	40	4045
14	40	4045
2	41	4051
14	41	4051
2	81	4059
14	81	4059
2	81	4178
4	81	4178
2	16	4235
4	16	4235
2	81	4302
14	81	4302
2	81	4303
14	81	4303
```

Les accès :
```
1	invité
2	magasin avec pouvoir de commande
3	vendeur service
4	correspondant E+S
5	directeur du site
6	dms
7	sdpv
9	préparateur sans pouvoir de commande
11	grands comptes
10	direction membre
12	AdminFc
13	Fc Vendeur UNIQUEMENT
14	AchatFichierCentral
```

**Comment by AlainPierreSDPV** [comment]
Ci joint la table modifiée à substituer
[Table KLS ex scouarnec.xlsx](https://github.com/groupe-gac/Portail-SDPV/files/724033/Table.KLS.ex.scouarnec.xlsx)

**Comment by AlainPierreSDPV** [comment]
ne pas tenir compte de la table; elle est incomplète
je poste une nouvelle table  dans qq miniutes

**Comment by AlainPierreSDPV** [comment]
Table à utiliser
[Table KLS ex scouarnec(2).xlsx](https://github.com/groupe-gac/Portail-SDPV/files/724075/Table.KLS.ex.scouarnec.2.xlsx)

**Comment by AlainPierreSDPV** [comment]
Je clos cette issue, le transfert des utilisateurs est conforme
