### ISSUE TITLE
mettre en pause le tracking luckyorange

### ISSUE THREAD

**Issue by jlenormant** [groupe-gac/Portail-SDPV#5]
demande liée au b2b : trop de pageviews sur sdpv.com, le neutraliser pour l'instant

**Comment by jlenormant** [comment]
note : si on souhaite le réactiver il faudra neutraliser les utilisateurs sdpv et waybis, et éventuellement ne pas le mettre sur certaines parties du site

**Comment by Paulhac** [comment]
j'ai retiré LuckyOrange.

**Comment by jlenormant** [comment]
merci
