### ISSUE TITLE
CAP VI : E-CAT nouvelle version

### ISSUE THREAD

**Issue by MamboJoel** [groupe-gac/Portail-SDPV#6]
Message de André AZEVEDO

> Bonsoir Alexiane, bonsoir Willy,
> 
> j'espère que vous allez bien,
> 
> je reviens vers vous concernant la mise en production de notre nouveau catalogue électronique,
> 
> comme précisé, lors de mes derniers mails, nous sommes sur une refonte total de notre catalogue électronique,
> 
> cette refonte nous permettra, enfin, de sortir de nos applets et de JAVA, il n'y aura donc plus de problème de connexion pour la franchise,
> 
> la mise en production est prévue pour le 1° Mars 2017,
> 
> à ce titre et au regard de notre e-cat encapsulé dans votre portail, cela va nécessiter une mise en œuvre auprès de votre webmaster,
> 
> François Edom, qui nous lit en copie ( Tel n° 04/77/49/49/81 ) a en charge votre dossier.
> 
> Votre Webmaster peut il se mettre en relation avec François afin qu'il lui présenter le projet, la mise en œuvre nécessaire et la phase de test que nous souhaitons mettre en place afin de minimiser au maximum les risques liés à la mise en production.
> 
> Je vous joins des documents relatifs au changement, merci de les faire suivre.
> 
> Dans l'attente de votre retour
> 
> Bien à vous
> 
> André AZEVEDO - Responsable Commercial France

**Comment by MamboJoel** [comment]
Le catalogue CapVI est disponible sur l'actuel portail pièces via une iframe. 

CapVI a changé son système d'authentification pour du SSO. Il faut désormais passer à cette iframe un jeton d'authentification via un paramètre de l'url.

Ils nous ont gentiment implémenté un projet VB.Net de démonstration qui contient une méthode qui retourne cette url :

   ``` VB.Net
    ''' <summary>
    ''' Cette methode permet de calculer l'url d'accès à l'E-Cat avec un token sso valide
    ''' </summary>
    ''' <param name="serverSsoUrl">Url du server sso de l'E-Cat ex: http://ecat.capvi.com/sso/auth</param>
    ''' <param name="baseEcatrUrl">Url du catalogue capvi. Ex:http://ecat.capvi.com/ecatpl</param>
    ''' <param name="errorUrl">Url de la page d'erreur sur le portail pièces</param>
    ''' <param name="auid">Identifiant du l'utilisateur SDPV, qui doit être crypté selon Waybis.Misc.Crypto.Encrypt</param>
    ''' <param name="origin">soit : "SDPV"</param>
    ''' <returns>String</returns>
    Public Shared Function getEcatUrl(ByVal serverSsoUrl As String, ByVal baseEcatrUrl As String, ByVal errorUrl As String, ByVal auid As String, ByVal origin As String) As String
```

Mon problème est que l'actuel portail est en ASP3. L'implémentation qu'ils fournissent est en ASP.Net. Je propose donc de l'intégrer dans une solution ASP.Net existante et j'ai pensé naturellement au B2B2C. Une page de cette application appellerait `getEcatUrl` et redirigerait vers la chaîne de caractères qu'elle retourne. C'est alors vers cette page du B2B2C que pointerait l'iframe de l'actuel portail pièces.

@jlenormant : 

- Est-ce que tu y vois un inconvénient ?
- Est-ce qu'on doit mener une réflexion plus en altitude quant à l'intégration demain de CAPVI sur le B2B2C, afin que ce développement soit compatible ?


[Voici leur implémentation](https://github.com/groupe-gac/Portail-SDPV/files/745218/Exemple.integration.sso.zip).

**Comment by jlenormant** [comment]
Je n'y vois pas d'inconvénient.

Une question que je me pose est la possibilité d'avoir accès à ce catalogue par des webservices, ou à la limite une iframe en marque blanche, de façon à envisager de l'intégrer du côté des clients concession, @WillySDPV qu'en penses-tu ?

**Comment by MamboJoel** [comment]
Ok Jean. On effectue l'intégration. Est-ce que tu es à jour de commit / sync de ce repository ? Car je vais devoir pousser la dll à l'issu du développement.

**Comment by MamboJoel** [comment]
@jlenormant il faudrait que tu commit et synchronises sdpv-gerausiv car il me manque `Vehicle3A.GetFieldsAsDataTable()`

Aussi, j'ai une erreur ligne 101 dans HTTPHelpers.vb :

```VB.Net
Return WebUtility.UrlEncode(stringToEncode)
```
'UrlEncode' n'est pas un membre de 'WebUtility'.

**Comment by jlenormant** [comment]
ok, le GetFieldsAsDataTable c'est à ajout sur waybis-common dans la classe entity
pour webutility je ne vois pas, c'est un projet séparé ou c'est dans le B2B ?

**Comment by jlenormant** [comment]
j'ai poussé deux/trois modifs sur sdpv-gestion et sdpv-b2b

**Comment by MamboJoel** [comment]
J'ai bien récupérée les modifs merci.
Reste l'erreur sur WebUtility.
Il s'agit semble-t-il d'une class de System.Net
B2B fait appel, ligne 101 dans HTTPHelpers.vb, à une méthode UrlEncode qui n'existe pas chez moi...

**Comment by jlenormant** [comment]
Je ne vois pas de fichier HTTPHelpers.vb

**Comment by MamboJoel** [comment]
Ah ! T'embêtes pas avec ça. C'est du code fourni par un prestataire de CAPVI qui plante comme ça.

**Comment by MamboJoel** [comment]
Je le pousse.

**Comment by jlenormant** [comment]
ah ok

**Comment by MamboJoel** [comment]
La nouvelle version de l'ecat de CAPVI est intégrée ce soir dans le portail.
